/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace HeThongTuyenDung {
  export type ChungChiStruct = {
    maChungChi: string;
    tenChungChi: string;
    hashDuLieu: string;
    nguoiCap: AddressLike;
    ngayCap: BigNumberish;
    hopLe: boolean;
  };

  export type ChungChiStructOutput = [
    maChungChi: string,
    tenChungChi: string,
    hashDuLieu: string,
    nguoiCap: string,
    ngayCap: bigint,
    hopLe: boolean
  ] & {
    maChungChi: string;
    tenChungChi: string;
    hashDuLieu: string;
    nguoiCap: string;
    ngayCap: bigint;
    hopLe: boolean;
  };

  export type CongViecStruct = {
    id: BigNumberish;
    nhaTuyenDung: AddressLike;
    tenCongViec: string;
    moTa: string;
    yeuCau: string;
    maChungChiYeuCau: string;
    ngayDang: BigNumberish;
    dangMo: boolean;
  };

  export type CongViecStructOutput = [
    id: bigint,
    nhaTuyenDung: string,
    tenCongViec: string,
    moTa: string,
    yeuCau: string,
    maChungChiYeuCau: string,
    ngayDang: bigint,
    dangMo: boolean
  ] & {
    id: bigint;
    nhaTuyenDung: string;
    tenCongViec: string;
    moTa: string;
    yeuCau: string;
    maChungChiYeuCau: string;
    ngayDang: bigint;
    dangMo: boolean;
  };

  export type HoSoUngTuyenStruct = {
    idCongViec: BigNumberish;
    ungVien: AddressLike;
    maChungChiNop: string;
    hashChungChi: string;
    ngayNop: BigNumberish;
    trangThai: BigNumberish;
    daXacMinh: boolean;
    ketQuaXacMinh: boolean;
  };

  export type HoSoUngTuyenStructOutput = [
    idCongViec: bigint,
    ungVien: string,
    maChungChiNop: string,
    hashChungChi: string,
    ngayNop: bigint,
    trangThai: bigint,
    daXacMinh: boolean,
    ketQuaXacMinh: boolean
  ] & {
    idCongViec: bigint;
    ungVien: string;
    maChungChiNop: string;
    hashChungChi: string;
    ngayNop: bigint;
    trangThai: bigint;
    daXacMinh: boolean;
    ketQuaXacMinh: boolean;
  };
}

export interface HeThongTuyenDungInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "capChungChi"
      | "daNopHoSo"
      | "dangKyNhaPhatHanh"
      | "dangKyNhaTuyenDung"
      | "dangKyUngVien"
      | "dangTuyenDung"
      | "danhSachChungChi"
      | "danhSachChungChiDaCap"
      | "danhSachCongViec"
      | "danhSachVaiTro"
      | "hoSoTheoCongViec"
      | "layDanhSachChungChi"
      | "layDanhSachChungChiDaCap"
      | "layDanhSachCongViec"
      | "layDanhSachHoSo"
      | "layVaiTro"
      | "nopHoSoUngTuyen"
      | "quyetDinhTuyenDung"
      | "xacMinhChungChi"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DaCapChungChi"
      | "DaDangKyVaiTro"
      | "DaDangTinTuyenDung"
      | "DaNopHoSo"
      | "DaRaQuyetDinh"
      | "DaXacMinhChungChi"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "capChungChi",
    values: [AddressLike, string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "daNopHoSo",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "dangKyNhaPhatHanh",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "dangKyNhaTuyenDung",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "dangKyUngVien",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "dangTuyenDung",
    values: [string, string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "danhSachChungChi",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "danhSachChungChiDaCap",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "danhSachCongViec",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "danhSachVaiTro",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hoSoTheoCongViec",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "layDanhSachChungChi",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "layDanhSachChungChiDaCap",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "layDanhSachCongViec",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "layDanhSachHoSo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "layVaiTro",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nopHoSoUngTuyen",
    values: [BigNumberish, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "quyetDinhTuyenDung",
    values: [BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "xacMinhChungChi",
    values: [BigNumberish, BigNumberish, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "capChungChi",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "daNopHoSo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "dangKyNhaPhatHanh",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dangKyNhaTuyenDung",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dangKyUngVien",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dangTuyenDung",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "danhSachChungChi",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "danhSachChungChiDaCap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "danhSachCongViec",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "danhSachVaiTro",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hoSoTheoCongViec",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "layDanhSachChungChi",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "layDanhSachChungChiDaCap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "layDanhSachCongViec",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "layDanhSachHoSo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "layVaiTro", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nopHoSoUngTuyen",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "quyetDinhTuyenDung",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "xacMinhChungChi",
    data: BytesLike
  ): Result;
}

export namespace DaCapChungChiEvent {
  export type InputTuple = [
    ungVien: AddressLike,
    maChungChi: string,
    nguoiCap: AddressLike
  ];
  export type OutputTuple = [
    ungVien: string,
    maChungChi: string,
    nguoiCap: string
  ];
  export interface OutputObject {
    ungVien: string;
    maChungChi: string;
    nguoiCap: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DaDangKyVaiTroEvent {
  export type InputTuple = [viNguoiDung: AddressLike, vaiTro: BigNumberish];
  export type OutputTuple = [viNguoiDung: string, vaiTro: bigint];
  export interface OutputObject {
    viNguoiDung: string;
    vaiTro: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DaDangTinTuyenDungEvent {
  export type InputTuple = [
    idCongViec: BigNumberish,
    nhaTuyenDung: AddressLike
  ];
  export type OutputTuple = [idCongViec: bigint, nhaTuyenDung: string];
  export interface OutputObject {
    idCongViec: bigint;
    nhaTuyenDung: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DaNopHoSoEvent {
  export type InputTuple = [idCongViec: BigNumberish, ungVien: AddressLike];
  export type OutputTuple = [idCongViec: bigint, ungVien: string];
  export interface OutputObject {
    idCongViec: bigint;
    ungVien: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DaRaQuyetDinhEvent {
  export type InputTuple = [
    idCongViec: BigNumberish,
    ungVien: AddressLike,
    trangThai: BigNumberish
  ];
  export type OutputTuple = [
    idCongViec: bigint,
    ungVien: string,
    trangThai: bigint
  ];
  export interface OutputObject {
    idCongViec: bigint;
    ungVien: string;
    trangThai: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DaXacMinhChungChiEvent {
  export type InputTuple = [
    idCongViec: BigNumberish,
    ungVien: AddressLike,
    ketQua: boolean
  ];
  export type OutputTuple = [
    idCongViec: bigint,
    ungVien: string,
    ketQua: boolean
  ];
  export interface OutputObject {
    idCongViec: bigint;
    ungVien: string;
    ketQua: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface HeThongTuyenDung extends BaseContract {
  connect(runner?: ContractRunner | null): HeThongTuyenDung;
  waitForDeployment(): Promise<this>;

  interface: HeThongTuyenDungInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  capChungChi: TypedContractMethod<
    [
      _ungVien: AddressLike,
      _maChungChi: string,
      _tenChungChi: string,
      _hashDuLieu: string
    ],
    [void],
    "nonpayable"
  >;

  daNopHoSo: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  dangKyNhaPhatHanh: TypedContractMethod<[], [void], "nonpayable">;

  dangKyNhaTuyenDung: TypedContractMethod<[], [void], "nonpayable">;

  dangKyUngVien: TypedContractMethod<[], [void], "nonpayable">;

  dangTuyenDung: TypedContractMethod<
    [_ten: string, _moTa: string, _yeuCau: string, _maChungChiYeuCau: string],
    [void],
    "nonpayable"
  >;

  danhSachChungChi: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [string, string, string, string, bigint, boolean] & {
        maChungChi: string;
        tenChungChi: string;
        hashDuLieu: string;
        nguoiCap: string;
        ngayCap: bigint;
        hopLe: boolean;
      }
    ],
    "view"
  >;

  danhSachChungChiDaCap: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [string, string, string, string, bigint, boolean] & {
        maChungChi: string;
        tenChungChi: string;
        hashDuLieu: string;
        nguoiCap: string;
        ngayCap: bigint;
        hopLe: boolean;
      }
    ],
    "view"
  >;

  danhSachCongViec: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, string, string, bigint, boolean] & {
        id: bigint;
        nhaTuyenDung: string;
        tenCongViec: string;
        moTa: string;
        yeuCau: string;
        maChungChiYeuCau: string;
        ngayDang: bigint;
        dangMo: boolean;
      }
    ],
    "view"
  >;

  danhSachVaiTro: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  hoSoTheoCongViec: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [bigint, string, string, string, bigint, bigint, boolean, boolean] & {
        idCongViec: bigint;
        ungVien: string;
        maChungChiNop: string;
        hashChungChi: string;
        ngayNop: bigint;
        trangThai: bigint;
        daXacMinh: boolean;
        ketQuaXacMinh: boolean;
      }
    ],
    "view"
  >;

  layDanhSachChungChi: TypedContractMethod<
    [_ungVien: AddressLike],
    [HeThongTuyenDung.ChungChiStructOutput[]],
    "view"
  >;

  layDanhSachChungChiDaCap: TypedContractMethod<
    [_nph: AddressLike],
    [HeThongTuyenDung.ChungChiStructOutput[]],
    "view"
  >;

  layDanhSachCongViec: TypedContractMethod<
    [],
    [HeThongTuyenDung.CongViecStructOutput[]],
    "view"
  >;

  layDanhSachHoSo: TypedContractMethod<
    [_idCongViec: BigNumberish],
    [HeThongTuyenDung.HoSoUngTuyenStructOutput[]],
    "view"
  >;

  layVaiTro: TypedContractMethod<[_vi: AddressLike], [bigint], "view">;

  nopHoSoUngTuyen: TypedContractMethod<
    [_idCongViec: BigNumberish, _maChungChiNop: string, _hashChungChi: string],
    [void],
    "nonpayable"
  >;

  quyetDinhTuyenDung: TypedContractMethod<
    [_idCongViec: BigNumberish, _indexHoSo: BigNumberish, _tuyenDung: boolean],
    [void],
    "nonpayable"
  >;

  xacMinhChungChi: TypedContractMethod<
    [_idCongViec: BigNumberish, _indexHoSo: BigNumberish, _ketQua: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "capChungChi"
  ): TypedContractMethod<
    [
      _ungVien: AddressLike,
      _maChungChi: string,
      _tenChungChi: string,
      _hashDuLieu: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "daNopHoSo"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "dangKyNhaPhatHanh"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "dangKyNhaTuyenDung"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "dangKyUngVien"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "dangTuyenDung"
  ): TypedContractMethod<
    [_ten: string, _moTa: string, _yeuCau: string, _maChungChiYeuCau: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "danhSachChungChi"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [string, string, string, string, bigint, boolean] & {
        maChungChi: string;
        tenChungChi: string;
        hashDuLieu: string;
        nguoiCap: string;
        ngayCap: bigint;
        hopLe: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "danhSachChungChiDaCap"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [string, string, string, string, bigint, boolean] & {
        maChungChi: string;
        tenChungChi: string;
        hashDuLieu: string;
        nguoiCap: string;
        ngayCap: bigint;
        hopLe: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "danhSachCongViec"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, string, string, bigint, boolean] & {
        id: bigint;
        nhaTuyenDung: string;
        tenCongViec: string;
        moTa: string;
        yeuCau: string;
        maChungChiYeuCau: string;
        ngayDang: bigint;
        dangMo: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "danhSachVaiTro"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "hoSoTheoCongViec"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [bigint, string, string, string, bigint, bigint, boolean, boolean] & {
        idCongViec: bigint;
        ungVien: string;
        maChungChiNop: string;
        hashChungChi: string;
        ngayNop: bigint;
        trangThai: bigint;
        daXacMinh: boolean;
        ketQuaXacMinh: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "layDanhSachChungChi"
  ): TypedContractMethod<
    [_ungVien: AddressLike],
    [HeThongTuyenDung.ChungChiStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "layDanhSachChungChiDaCap"
  ): TypedContractMethod<
    [_nph: AddressLike],
    [HeThongTuyenDung.ChungChiStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "layDanhSachCongViec"
  ): TypedContractMethod<[], [HeThongTuyenDung.CongViecStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "layDanhSachHoSo"
  ): TypedContractMethod<
    [_idCongViec: BigNumberish],
    [HeThongTuyenDung.HoSoUngTuyenStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "layVaiTro"
  ): TypedContractMethod<[_vi: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "nopHoSoUngTuyen"
  ): TypedContractMethod<
    [_idCongViec: BigNumberish, _maChungChiNop: string, _hashChungChi: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "quyetDinhTuyenDung"
  ): TypedContractMethod<
    [_idCongViec: BigNumberish, _indexHoSo: BigNumberish, _tuyenDung: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "xacMinhChungChi"
  ): TypedContractMethod<
    [_idCongViec: BigNumberish, _indexHoSo: BigNumberish, _ketQua: boolean],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "DaCapChungChi"
  ): TypedContractEvent<
    DaCapChungChiEvent.InputTuple,
    DaCapChungChiEvent.OutputTuple,
    DaCapChungChiEvent.OutputObject
  >;
  getEvent(
    key: "DaDangKyVaiTro"
  ): TypedContractEvent<
    DaDangKyVaiTroEvent.InputTuple,
    DaDangKyVaiTroEvent.OutputTuple,
    DaDangKyVaiTroEvent.OutputObject
  >;
  getEvent(
    key: "DaDangTinTuyenDung"
  ): TypedContractEvent<
    DaDangTinTuyenDungEvent.InputTuple,
    DaDangTinTuyenDungEvent.OutputTuple,
    DaDangTinTuyenDungEvent.OutputObject
  >;
  getEvent(
    key: "DaNopHoSo"
  ): TypedContractEvent<
    DaNopHoSoEvent.InputTuple,
    DaNopHoSoEvent.OutputTuple,
    DaNopHoSoEvent.OutputObject
  >;
  getEvent(
    key: "DaRaQuyetDinh"
  ): TypedContractEvent<
    DaRaQuyetDinhEvent.InputTuple,
    DaRaQuyetDinhEvent.OutputTuple,
    DaRaQuyetDinhEvent.OutputObject
  >;
  getEvent(
    key: "DaXacMinhChungChi"
  ): TypedContractEvent<
    DaXacMinhChungChiEvent.InputTuple,
    DaXacMinhChungChiEvent.OutputTuple,
    DaXacMinhChungChiEvent.OutputObject
  >;

  filters: {
    "DaCapChungChi(address,string,address)": TypedContractEvent<
      DaCapChungChiEvent.InputTuple,
      DaCapChungChiEvent.OutputTuple,
      DaCapChungChiEvent.OutputObject
    >;
    DaCapChungChi: TypedContractEvent<
      DaCapChungChiEvent.InputTuple,
      DaCapChungChiEvent.OutputTuple,
      DaCapChungChiEvent.OutputObject
    >;

    "DaDangKyVaiTro(address,uint8)": TypedContractEvent<
      DaDangKyVaiTroEvent.InputTuple,
      DaDangKyVaiTroEvent.OutputTuple,
      DaDangKyVaiTroEvent.OutputObject
    >;
    DaDangKyVaiTro: TypedContractEvent<
      DaDangKyVaiTroEvent.InputTuple,
      DaDangKyVaiTroEvent.OutputTuple,
      DaDangKyVaiTroEvent.OutputObject
    >;

    "DaDangTinTuyenDung(uint256,address)": TypedContractEvent<
      DaDangTinTuyenDungEvent.InputTuple,
      DaDangTinTuyenDungEvent.OutputTuple,
      DaDangTinTuyenDungEvent.OutputObject
    >;
    DaDangTinTuyenDung: TypedContractEvent<
      DaDangTinTuyenDungEvent.InputTuple,
      DaDangTinTuyenDungEvent.OutputTuple,
      DaDangTinTuyenDungEvent.OutputObject
    >;

    "DaNopHoSo(uint256,address)": TypedContractEvent<
      DaNopHoSoEvent.InputTuple,
      DaNopHoSoEvent.OutputTuple,
      DaNopHoSoEvent.OutputObject
    >;
    DaNopHoSo: TypedContractEvent<
      DaNopHoSoEvent.InputTuple,
      DaNopHoSoEvent.OutputTuple,
      DaNopHoSoEvent.OutputObject
    >;

    "DaRaQuyetDinh(uint256,address,uint8)": TypedContractEvent<
      DaRaQuyetDinhEvent.InputTuple,
      DaRaQuyetDinhEvent.OutputTuple,
      DaRaQuyetDinhEvent.OutputObject
    >;
    DaRaQuyetDinh: TypedContractEvent<
      DaRaQuyetDinhEvent.InputTuple,
      DaRaQuyetDinhEvent.OutputTuple,
      DaRaQuyetDinhEvent.OutputObject
    >;

    "DaXacMinhChungChi(uint256,address,bool)": TypedContractEvent<
      DaXacMinhChungChiEvent.InputTuple,
      DaXacMinhChungChiEvent.OutputTuple,
      DaXacMinhChungChiEvent.OutputObject
    >;
    DaXacMinhChungChi: TypedContractEvent<
      DaXacMinhChungChiEvent.InputTuple,
      DaXacMinhChungChiEvent.OutputTuple,
      DaXacMinhChungChiEvent.OutputObject
    >;
  };
}
