/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { HeThongTuyenDung } from "./HeThongTuyenDung";
export * as factories from "./factories";
export { HeThongTuyenDung__factory } from "./factories/HeThongTuyenDung__factory";
